### ISSUE TITLE
can not pull image after docker login

### ISSUE THREAD

**Issue by glorysdj** [mdrakiburrahman/sgx-pyspark-sql-demo#4]
when try to run this on k8s
```
# Login to Scone's container registry (after receiving access to Gitlab)
docker login registry.scontain.com:5050 -u your--scone--gitlab--username -p your--scone--gitlab--password

# Pull PySpark Container image
docker pull registry.scontain.com:5050/clenimar/pyspark:5.5.0-amd-experimental-k8s
```
after the step 1 docker Login Succeeded
the step 2 failed,
Error response from daemon: pull access denied for registry.scontain.com:5050/clenimar/pyspark, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Any idea?

**Comment by clenimar** [comment]
Hi @glorysdj, the PySpark image has to be given explicit access by me (because it hasn't been released yet). What's your username there?

**Comment by glorysdj** [comment]
Hi @clenimar my username is glorysdj. Thanks.

**Comment by clenimar** [comment]
@glorysdj done.

**Comment by glorysdj** [comment]
thanks, it works.
